# Generated by Django 4.2.8 on 2023-12-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayplanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
