# Generated by Django 4.2.8 on 2024-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
